# 最も接続成功率が高い設定です
# ポートが 5432 になっていることを必ず確認
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.gubwpggvjfmhkwccotyq&password=${DB_PASSWORD}


spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# IPv4優先のためのJavaオプション（これを追加してください）
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 起動時にデータベースの接続詳細（URLやパスワード等）をログに出さないようにする設定
logging.level.org.hibernate.orm.connections.pooling=WARN
logging.level.org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator=WARN
# 開発用テストアカウントを明示的に指定して、ランダムパスワードの自動生成ログを止める
spring.security.user.name=devuser
spring.security.user.password=devpassword123


# セキュリティ設定（後ほどJWT用に拡張します）
# 最初は動作確認のためSecurityを少し緩める設定を後ほど追加します

## Supabaseの代わりに、PC内部のメモリ上のDBを使います
#spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## 起動時にテーブルを自動作成する設定（開発が楽になります）
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
